name = "CountyClusteringNotebook"
uuid = "9bd20f9b-06ff-40ee-bf37-aa2b3373d8a4"
authors = ["Matthew Helm"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
